name: Check Tags Workflow

on:
  push:
    branches:
      - main

jobs:
  check_tags:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get latest tag
      id: latest-tag
      run: |
        echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_STATE

    - name: Get previous tag
      id: previous-tag
      run: |
        PREVIOUS_TAG=$(git describe --tags --abbrev=0)
        echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_STATE

    - name: Debug Tags
      run: | 
        echo "Previous tag: $PREVIOUS_TAG"
        echo "Latest tag: $LATEST_TAG"
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT
        echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
