name: Check Tags Workflow

on:
  push:
    branches:
      - main

jobs:
  check_tags:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get latest tag
      id: latest-tag
      run: |
        LATEST_TAG=$(git describe --tags --abbrev=0) >> $GITHUB_OUTPUT
        echo $LATEST_TAG
        

    - name: Get previous tag
      id: previous-tag
      run: |
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 -n 1)) >> $GITHUB_OUTPUT
        echo "PREVIOUS_TAG=$PREVIOUS_TAG" 

    - name: Debug Tags
      run: | 
        LATEST_TAG=${{ steps.latest-tag.outputs.LATEST_TAG }} >> $GITHUB_ENV
        echo $LATEST_TAG
