name: Check Tags Workflow

on: [push]

jobs:
  check_tags:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Get latest and previous tags
      id: get_tags
      run: |
        # Get the latest tag
        latest_tag=$(git describe --tags --abbrev=0)
        echo "Latest tag: $latest_tag"

        # Get the previous tag
        previous_tag=$(git describe --tags --abbrev=0 $latest_tag^)
        echo "Previous tag: $previous_tag"

        # Pass the tags as output variables
        echo "::set-output name=latest_tag::$latest_tag"
        echo "::set-output name=previous_tag::$previous_tag"

    - name: Get commit messages
      id: get_commit_messages
      run: |
        # Get commit messages between previous tag and latest tag
        commit_messages=$(git log --pretty=format:"%s" ${{ steps.get_tags.outputs.previous_tag }}..${{ steps.get_tags.outputs.latest_tag }})
        echo "Commit messages between ${{ steps.get_tags.outputs.previous_tag }} and ${{ steps.get_tags.outputs.latest_tag }}:"
        echo "$commit_messages"

      # Print the commit messages as an output
      env:
        COMMIT_MESSAGES: ${{ steps.get_commit_messages.outputs.commit_messages }}
    
    - name: Use commit messages
      run: |
        # Use $COMMIT_MESSAGES in your further steps or scripts
        echo "$COMMIT_MESSAGES"
