name: Check Tags Workflow

on: [push]

jobs:
  check_tags:
    runs-on: ubuntu-latest

    outputs:
      LATEST_TAG: ${{ steps.latest-tag.outputs.LATEST_TAG }}
      PREVIOUS_TAG: ${{ steps.previous-tag.outputs.PREVIOUS_TAG }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: get latest tag
      id: latest-tag
      run: |
        LATEST_TAG=$(git describe --tags --abbrev=0)
        echo "Latest tag: $LATEST_TAG" >> "$GITHUB_OUTPUT"
        echo "Latest tag: $LATEST_TAG"

    - name: get previous tag
      id: previous-tag
      run: |
        PREVIOUS_TAG=$(git describe --tags --abbrev=0)
        echo "Previous tag: $PREVIOUS_TAG" >> "$GITHUB_OUTPUT"
        echo "Previous tag: $PREVIOUS_TAG"

    - name: Debug Tags
      run: | 
        echo "Previous tag: $PREVIOUS_TAG"
        echo "Latest tag: $LATEST_TAG"
