name: Check Tags WorkflowW

on:
  push:
    branches:
      - main

jobs:
  check_tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install git, jira for python
        run: |
          pip3 install -q GitPython==3.1.40    

      - name: Get latest tag
        id: latest-tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0) 
          echo "LATEST_TAG=${LATEST_TAG}" >> "$GITHUB_ENV"
          
      - name: Get previous tag
        id: previous-tag
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 -n 1)) 
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> "$GITHUB_ENV"

      - name: Debug Tags
        run: | 
          echo "the latest tag is ${LATEST_TAG}"
          echo "the PREVIOUS tag is ${PREVIOUS_TAG}"
 
      - name: Generate changelog
        shell: python
        env:
          TOKEN: ${{ secrets.TEST }}
        run: |
          import git
          import re
          import http.client
          import json
          import os
          
          repo_path = 'C:\\projects\\change-log'
          conn = http.client.HTTPSConnection("api.github.com")
          token = os.environ['TOKEN']
          payload = ""
          token = "Bearer " + token
         
          headers = {
              'content-type': "application/json; charset=utf-8",
              'Authorization': token,
              'User-Agent': 'Your-User-Agent-Name'
          }
          
          repo = git.Repo(search_parent_directories=True)
          
          # Get the latest tag
          latest_tag = repo.tags[-1]
          previous_tag = os.environ['PREVIOUS_TAG']
          
          # Define patterns for commit messages
          patterns = [r'(?:^\[)(\b[A-Z][A-Z0-9_]+-[1-9][0-9]*)(?:\])']
          
          # Compile regex patterns
          regex_patterns = [re.compile(pattern) for pattern in patterns]
          
          # Iterate over commits from the latest tag
          commits_since_latest_tag = list(repo.iter_commits(f"4.0.0..5.0.0", no_merges=True))
          ls_store = []
          for commit in commits_since_latest_tag:
              message = commit.message.strip()
              for pattern in regex_patterns:
                  if pattern.match(commit.message.strip()):
                      sha = str(commit.hexsha)
                      conn.request("GET", f"/repos/kashyaprakshith/change-log/commits/{sha}/pulls", payload, headers)
                      response = conn.getresponse()
                      data = response.read().decode("utf-8")
                      info = json.loads(data)
                      data = response.read().decode("utf-8")  
                      html_href = info[0].get('_links', {}).get('html', {}).get('href', '') 
                      author_name = commit.author.name 
                      # extract the PR Number
                      link = f"{html_href}"
                      pattern = r'/pull/(\d+)'
                      match = re.search(pattern, link)
                      if match:
                          number = match.group(1)
          
                      #print(f"Commit Message: {message}")
                      #print(f"PR-Link = {html_href}")
                      #print(f"Author: {author_name}")
                      #print(f"PR-NUMBER: {number}")
                      data = f"- {message} by {author_name} [#{number}]({html_href})"
                      ls_store.append(data)
          ls_store_str = "\n".join(ls_store)
          print(ls_store_str)
          print(previous_tag)
          modified = f'''RELEASE_NOTES<<EOF
          {ls_store_str}
          print
          EOF
          '''

          env_file = os.getenv('GITHUB_ENV')
          with open(env_file, "a") as myfile:
               myfile.write(modified)
               
     # - name: get release notes 
     #   id: release-not
     #   run: |
     #     echo  "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
       #   echo -e "$NOTES" >> $GITHUB_ENV
     #     echo "EOF" >> $GITHUB_ENV

      - run: echo  "${{ env.RELEASE_NOTES }}"
          
      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ env.LATEST_TAG }}
          release-notes: |
            ${{ env.RELEASE_NOTES }}

      - name: Push new changelog
        run: |
          git add --update
          git config --global user.name "cofinity-x-version-bumper-bot[bot]"
          git config --global user.email "ghxjh@gmail.com"
          git commit -m "Changelog of changelog"
          git push origin      

     
